import ConfirmationValidator from './validators/confirmation.ts';
import CustomValidator from './validators/custom.ts';
import EmailValidator from './validators/email.ts';
import ExclusionValidator from './validators/exclusion.ts';
import FileValidator from './validators/file.ts';
import InclusionValidator from './validators/inclusion.ts';
import LengthValidator from './validators/length.ts';
import NumberValidator from './validators/number.ts';
import PasswordValidator from './validators/password.ts';
import PhoneValidator from './validators/phone.ts';
import PresenceValidator from './validators/presence.ts';
import RangeValidator from './validators/range.ts';
import RegexValidator from './validators/regex.ts';
import type { Computable, TranslatableOption, Validator } from './types.ts';
import type { Primitive } from '../index.ts';
import type { ConfirmationOptions } from './validators/confirmation.ts';
import type { CustomOptions } from './validators/custom.ts';
import type { EmailOptions } from './validators/email.ts';
import type { ExclusionOptions } from './validators/exclusion.ts';
import type { FileOptions } from './validators/file.ts';
import type { InclusionOptions } from './validators/inclusion.ts';
import type { LengthOptions } from './validators/length.ts';
import type { NumberOptions } from './validators/number.ts';
import type { PasswordOptions } from './validators/password.ts';
import type { PhoneOptions } from './validators/phone.ts';
import type { PresenceOptions } from './validators/presence.ts';
import type { RangeOptions } from './validators/range.ts';
import type { RegexOptions } from './validators/regex.ts';
declare const Validators: {
    confirmation: typeof ConfirmationValidator;
    custom: typeof CustomValidator;
    email: typeof EmailValidator;
    exclusion: typeof ExclusionValidator;
    file: typeof FileValidator;
    inclusion: typeof InclusionValidator;
    length: typeof LengthValidator;
    number: typeof NumberValidator;
    password: typeof PasswordValidator;
    phone: typeof PhoneValidator;
    presence: typeof PresenceValidator;
    range: typeof RangeValidator;
    regex: typeof RegexValidator;
};
type ValidatorType = keyof typeof Validators;
declare type OptionsOf<T extends ValidatorType> = ConstructorParameters<(typeof Validators)[T]>[1];
type ValidatorFnArgs<V extends ValidatorType = ValidatorType, Context extends object = object> = V extends V ? [V, OptionsOf<V>, Context | undefined] | [V, OptionsOf<V>] : never;
export declare function validator<Context extends object = object, T = unknown, V extends ValidatorType = ValidatorType>(...[type, options, context]: ValidatorFnArgs<V, Context>): Validator<unknown, Context, OptionsOf<V>>;
export declare function confirmation<Context extends object = object>(options: Computable<Context, ConfirmationOptions>, context?: Context): Validator<TranslatableOption, Context, ConfirmationOptions>;
export declare function custom<Context extends object = object, T = unknown>(options: Computable<Context, CustomOptions<T, Context>>, context?: Context): Validator<T, Context, CustomOptions<T, Context>>;
export declare function email<Context extends object = object>(options: Computable<Context, EmailOptions>, context?: Context): Validator<string, Context, EmailOptions>;
export declare function exclusion<Context extends object = object, T extends Primitive = Primitive>(options: Computable<Context, ExclusionOptions<T>>, context?: Context): Validator<T, Context, ExclusionOptions<T>>;
export declare function file<Context extends object = object>(options: Computable<Context, FileOptions>, context?: Context): Validator<File | File[], Context, FileOptions>;
export declare function inclusion<Context extends object = object, T extends Primitive = Primitive>(options: Computable<Context, InclusionOptions<T>>, context?: Context): Validator<T, Context, InclusionOptions<T>>;
export declare function length<Context extends object = object, T extends ArrayLike<unknown> = ArrayLike<unknown>>(options: Computable<Context, LengthOptions>, context?: Context): Validator<T, Context, LengthOptions>;
export declare function number<Context extends object = object>(options: Computable<Context, NumberOptions>, context?: Context): Validator<number, Context, NumberOptions>;
export declare function password<Context extends object = object>(options: Computable<Context, PasswordOptions>, context?: Context): Validator<string, Context, PasswordOptions>;
export declare function phone<Context extends object = object>(options: Computable<Context, PhoneOptions>, context?: Context): Validator<string, Context, PhoneOptions>;
export declare function presence<Context extends object = object, T = unknown>(options: Computable<Context, PresenceOptions>, context?: Context): Validator<T, Context, PresenceOptions>;
export declare function range<Context extends object = object>(options: Computable<Context, RangeOptions>, context?: Context): Validator<number, Context, RangeOptions>;
export declare function regex<Context extends object = object>(options: Computable<Context, RegexOptions>, context?: Context): Validator<string, Context, RegexOptions>;
export {};
