import Accordion from './components/accordion';
import Alert from './components/alert';
import AppBar from './components/app-bar';
import ButtonGroup from './components/button-group';
import Button from './components/button';
import Card from './components/card';
import Footer from './components/footer';
import BoundValue from './components/form/bound-value.ts';
import CheckboxGroup from './components/form/checkbox-group';
import Checkbox from './components/form/checkbox';
import Datetime from './components/form/datetime';
import Field from './components/form/field';
import FileUpload from './components/form/file-upload';
import Form from './components/form/index';
import NumberInput from './components/form/number-input';
import PhoneInput from './components/form/phone-input';
import RadioGroup from './components/form/radio-group';
import Select from './components/form/select';
import TextArea from './components/form/text-area';
import TextInput from './components/form/text-input';
import Header from './components/header';
import Icon from './components/icon';
import LoadingIndicator from './components/loading-indicator';
import MktgCardContainer from './components/mktg/card-container';
import MktgCard from './components/mktg/card';
import MktgFeatureList from './components/mktg/feature-list';
import MktgFooter from './components/mktg/footer';
import MktgHeader from './components/mktg/header';
import MktgNavbar from './components/mktg/navbar';
import MktgPromoContainer from './components/mktg/promo-container';
import MktgPromo from './components/mktg/promo';
import MktgSectionHeader from './components/mktg/section-header';
import MktgServicePricing from './components/mktg/service-pricing';
import MktgWorkflowTray from './components/mktg/workflow-tray';
import Modal from './components/modal';
import NavItem from './components/nav-item';
import PageNotFound from './components/page-not-found';
import Pagination from './components/pagination';
import Progress from './components/progress';
import Scaffold from './components/scaffold';
import Sidebar from './components/sidebar';
import { Container as StackedPaneContainer, Pane as StackedPane } from './components/stacked-pane';
import Toaster from './components/toaster';
import Bind from './helpers/bind.ts';
import LookupService from './helpers/lookup-service.ts';
import Version from './helpers/version.ts';
import OnClickOutside from './modifiers/on-click-outside.ts';
import OnInsert from './modifiers/on-insert.ts';
export interface ComponentRegistry {
    Accordion: typeof Accordion;
    Alert: typeof Alert;
    AppBar: typeof AppBar;
    ButtonGroup: typeof ButtonGroup;
    Button: typeof Button;
    Card: typeof Card;
    Footer: typeof Footer;
    Header: typeof Header;
    Icon: typeof Icon;
    LoadingIndicator: typeof LoadingIndicator;
    Modal: typeof Modal;
    NavItem: typeof NavItem;
    PageNotFound: typeof PageNotFound;
    Pagination: typeof Pagination;
    Progress: typeof Progress;
    Scaffold: typeof Scaffold;
    Sidebar: typeof Sidebar;
    StackedPane: typeof StackedPane;
    'StackedPane::Container': typeof StackedPaneContainer;
    Toaster: typeof Toaster;
    Form: typeof Form;
    'Form::BoundValue': typeof BoundValue;
    'Form::CheckboxGroup': typeof CheckboxGroup;
    'Form::Checkbox': typeof Checkbox;
    'Form::Datetime': typeof Datetime;
    'Form::Field': typeof Field;
    'Form::FileUpload': typeof FileUpload;
    'Form::NumberInput': typeof NumberInput;
    'Form::PhoneInput': typeof PhoneInput;
    'Form::RadioGroup': typeof RadioGroup;
    'Form::Select': typeof Select;
    'Form::TextArea': typeof TextArea;
    'Form::TextInput': typeof TextInput;
    'Mktg::CardContainer': typeof MktgCardContainer;
    'Mktg::Card': typeof MktgCard;
    'Mktg::FeatureList': typeof MktgFeatureList;
    'Mktg::Footer': typeof MktgFooter;
    'Mktg::Header': typeof MktgHeader;
    'Mktg::Navbar': typeof MktgNavbar;
    'Mktg::PromoContainer': typeof MktgPromoContainer;
    'Mktg::Promo': typeof MktgPromo;
    'Mktg::SectionHeader': typeof MktgSectionHeader;
    'Mktg::ServicePricing': typeof MktgServicePricing;
    'Mktg::WorkflowTray': typeof MktgWorkflowTray;
}
export interface HelperRegistry {
    bind: typeof Bind;
    'lookup-service': typeof LookupService;
    version: typeof Version;
}
export interface ModifierRegistry {
    'on-click-outside': typeof OnClickOutside;
    'on-insert': typeof OnInsert;
}
export default interface TemplateRegistry extends ComponentRegistry, HelperRegistry, ModifierRegistry {
}
