# Because this library needs to be built,
# we can't easily point package.json files at the git repo for easy cross-repo testing.
#
# This workflow brings back that capability by placing the compiled assets on a "dist" branch
# (configurable via the "branch" option below)
name: Publish (unstable)

on:
  push:
    branches:
      - main

jobs:
  push-dist:
    name: Push dist
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup PNPM
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Detect changes
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            app-version:
              - 'packages/app-version/**'
            code-snippets:
              - 'packages/code-snippets/**'
            design-system:
              - 'packages/design-system/**'
            ember-core:
              - 'packages/ember-core/**'
            standards:
              - 'packages/standards/**'
            showcase:
              - 'packages/showcase/**'
            theme-generator:
              - 'packages/theme-generator/**'

      - name: Publish `@nrg-ui/core`
        if: steps.filter.outputs.ember-core == 'true'
        uses: kategengler/put-built-npm-package-contents-on-branch@v2.1.0
        with:
          branch: unstable-ember
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: 'packages/ember-core'

      - name: Publish `@nrg-ui/css`
        if: steps.filter.outputs.design-system == 'true'
        uses: kategengler/put-built-npm-package-contents-on-branch@v2.1.0
        with:
          branch: unstable-css
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: 'packages/design-system'

      - name: Publish `@nrg-ui/standards`
        if: steps.filter.outputs.standards == 'true'
        uses: kategengler/put-built-npm-package-contents-on-branch@v2.1.0
        with:
          branch: unstable-standards
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: 'packages/standards'

      - name: Publish `@nrg-ui/app-version`
        if: steps.filter.outputs.app-version == 'true'
        uses: kategengler/put-built-npm-package-contents-on-branch@v2.1.0
        with:
          branch: unstable-app-version
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: 'packages/app-version'

      - name: Publish `@nrg-ui/code-snippets`
        if: steps.filter.outputs.code-snippets == 'true'
        uses: kategengler/put-built-npm-package-contents-on-branch@v2.1.0
        with:
          branch: unstable-code-snippets
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: 'packages/code-snippets'

      - name: Publish `@nrg-ui/showcase`
        if: steps.filter.outputs.showcase == 'true'
        uses: kategengler/put-built-npm-package-contents-on-branch@v2.1.0
        with:
          branch: unstable-showcase
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: 'packages/showcase'

      - name: Publish `@nrg-ui/theme-generator`
        if: steps.filter.outputs.theme-generator == 'true'
        uses: kategengler/put-built-npm-package-contents-on-branch@v2.1.0
        with:
          branch: unstable-theme-generator
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: 'packages/theme-generator'
