# Because this library needs to be built,
# we can't easily point package.json files at the git repo for easy cross-repo testing.
#
# This workflow brings back that capability by placing the compiled assets on a "dist" branch
# (configurable via the "branch" option below)
name: Push dist

on:
  push:
    branches:
      - main

jobs:
  push-dist:
    name: Push dist
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Node Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/yarn
            ~/.local/share/pnpm/store
          key: node-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - uses: kategengler/put-built-npm-package-contents-on-branch@v2.0.0
        with:
          branch: unstable-ember
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: 'packages/ember'

      - uses: kategengler/put-built-npm-package-contents-on-branch@v2.0.0
        with:
          branch: unstable-css
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: 'packages/design-system'
